language: php
php:
  - 7.3
  - 7.4
install: composer install --no-interaction --prefer-source
env:
  matrix:
    - VERIFICATION_TOOL=phpunit-checks
    - VERIFICATION_TOOL=static-checks
script:
  - bin/$VERIFICATION_TOOL
after_success:
  - travis_retry php vendor/bin/coveralls
