language: php
php:
  - 7.0
  - 7.1
install: composer install --no-interaction --prefer-source
matrix:
    - VERIFICATION_TOOL=copyright-check
    - VERIFICATION_TOOL=phpunit-checks
    - VERIFICATION_TOOL=static-checks
script:
  - bin/$VERIFICATION_TOOL
